vert_hist: vert_hist.c
	gcc -Wall -W -pedantic -o vert_hist vert_hist.c
tabutil: tabutil.c
	gcc -Wall -W -pedantic -o tabutil tabutil.c
life_engine: life_engine.c
	gcc -o life -Wall -W -pedantic life_engine.c life_driver.c
unscramble: unscramble.c
	gcc -Wall -W -pedantic -o unscramble unscramble.c
